server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/native # 임의의 경로
        git:
          uri: file:///Users/jaemin/Desktop/git-local-repo
#          uri: https://github.com/jakang
#          username: jakang
#          password: hello